### ISSUE TITLE
Remove Inline Styles

### ISSUE THREAD

**Issue by martindale** [RolePlayGateway/roleplaygateway#12]
Our templates are littered with inline styles; we could use the following CSS to highlight where this is the case:

```css
*[style] { 
    border: 5px solid red; /* Style to make the elements noticeable */
}
```

From [Linting HTML with CSS](https://bitsofco.de/linting-html-using-css/) by @ireade.
